#+title: MuColl LCIO -> EDM4hep conversion

* Simulation
** Generate test events
(All of this is happening in ~/data/~ which is bindmounted to the outside)
Generate a few pion particle gun events for testing

#+begin_src bash
python /opt/SteeringMacros/Gen/lcio_pion_gun_pT.py
#+end_src

** Simulate events
- Simulate only 100 of the 10k available events
- ~sim_steer_GEN_CONDOR.py~ needs a minor edit to define an outputfile name to
  avoid an undefined variable error
#+begin_src bash
cp /opt/SteeringMacros/Sim/sim_steer_BIB_CONDOR.py .
sed -i '/OUTFILENAME/s/^/# /' sim_steer_BIB_CONDOR.py
#+end_src

#+begin_src bash
ddsim --inputFile gen_pionGun.slcio \
    --steeringFile sim_steer_BIB_CONDOR.py \
    --outputFile pionGun_SIM.slcio \
    --compactFile /opt/detector-simulation/geometries/MuColl_10TeV_v0A/MuColl_10TeV_v0A.xml \
    -N 100
#+end_src

* Reconstruction
** Using Marlin

- Make sure that the paths in the ~PandoraSettingsDefault.xml~ point to the right place
#+begin_src bash
sed -i 's:/code/:/opt/:' /opt/SteeringMacros/Reco/PandoraSettings/PandoraSettingsDefault.xml
#+end_src

- Also adapt a few more paths where possible via the command line

#+begin_src bash
Marlin /opt/SteeringMacros/Reco/reco_CONDOR.xml \
    --global.LCIOInputFiles=pionGun_Sim.slcio \
    --Output_REC.LCIOOutputFile=pionGun_Rec.slcio \
    --InitDD4hep.DD4hepXMLFile=/opt/detector-simulation/geometries/MuColl_10TeV_v0A/MuColl_10TeV_v0A.xml \
    --CKFTracking.MatFile=/opt/spack/opt/spack/linux-ubuntu22.04-x86_64/gcc-11.3.0/actstracking-1.1.0-vk7dd4tkm75atbkawti2mfozyujq6db2/share/ACTSTracking/data/material-maps.json \
    --DDMarlinPandora.PandoraSettingsXmlFile=/opt/SteeringMacros/Reco/PandoraSettings/PandoraSettingsDefault.xml \
    --Config.Overlay=False
#+end_src

- [ ] This segfaults in ACTS tracking

** Using Gaudi / k4geo
*** preparation / data downloading
- Download BIB from ~snowmass/collab~ and store it in ~/data/BIB10TeV~
#+begin_src bash
mkdir -p /data/BIB10TeV
cd /data/BIB10TeV
rsync -az snowmass21:/collab/project/snowmass21/data/muonc/fmeloni/DataMuC_MuColl10_v0A/BIB10TeV/BIB_sim_m?.slcio .
#+end_src

*** Running
- We can use the Key4hep based steering file for this with some minor adaptions
- Export environment variables
#+begin_src bash
export GEOMETRY=/opt/detector-simulation
#+end_src
- Make ~InitDD4hep~ use that by updating the path from which the geometry is
  loaded. For this it is easiest to simply copy the original steering file and apply the changes there
#+begin_src bash
cp /opt/SteeringMacros/k4Reco/steer_reco.py .
sed -i '/DD4hepXMLFile/s|../detector-simulation|$GEOMETRY|' steer_reco.py
#+end_src
  In the end the ~InitDD4hep~ configuration should look like this:
#+begin_src python
InitDD4hep.Parameters = {
                         "DD4hepXMLFile": ["$GEOMETRY/geometries/MuColl_10TeV_v0A/MuColl_10TeV_v0A.xml"],
                         "EncodingStringParameterName": ["GlobalTrackerReadoutID"]
                         }
#+end_src
- Copy ~MarlinPandora~ steering files and slightly touch them up
#+begin_src bash
cp -r /opt/SteeringMacros/Reco/PandoraSettings .
sed -i 's|/code/SteeringMacros/Reco/||' PandoraSettings/PandoraSettingsDefault.xml
#+end_src
- Adapt outpufile name (optionally)
#+begin_src bash
sed -i '/LCIOOutputFile/s/\["\(.*\)"\]/["pionGun_REC.slcio"]/' steer_reco.py
#+end_src
- To avoid running into [[https://github.com/AIDASoft/podio/issues/462][issue in podio]] we also need to make sure that the
  ~SiTracks~ are not stored as a subset collection, by adding it to the
  ~FullSubsetCollections~ of the ~Output_REC~ processor.
#+begin_src bash
sed -i '/FullSubsetCollections/s/\]/, "SiTracks"\]/' steer_reco.py
#+end_src
now the configuration of the ~Output_REC~ processor should look like
#+begin_src python
Output_REC.Parameters = {
    "DropCollectionNames": [],
    "DropCollectionTypes": ["SimCalorimeterHit", "SimTrackerHit"],
    "FullSubsetCollections": ["EfficientMCParticles", "InefficientMCParticles", "SiTracks"],
    "KeepCollectionNames": ["MCParticle_SiTracks_Refitted"],
    "LCIOOutputFile": ["pionGun_REC.slcio"],
    "LCIOWriteMode": ["WRITE_NEW"]
}
#+end_src
- Enable ~OverlayBIB~ (and disable ~OverlayFalse~)
#+begin_src bash
sed -i '/# algList.append(OverlayBIB)/s/^# //' steer_reco.py
sed -i '/algList.append(OverlayFalse)/s/^/# /' steer_reco.py
#+end_src
- Run the script
#+begin_src bash
k4run steer_reco.py --LcioEvent.Files=pionGun_SIM.slcio -n 100
#+end_src

* Conversion
** Build a suitable LCIO version
In order to run the standalone conversion we need to build an updated version of
LCIO, because some of the functionality has not yet been backported to the
~muoncollidersoft~ version of LCIO

Until it is merged we build off of [[https://github.com/muoncollidersoft/LCIO/pull/6][this PR]] which can be most easily obtained via
#+begin_src bash
git clone --depth 1 -b backport-patch-coll-fixes https://github.com/tmadlener/LCIO
#+end_src

Afterwards we build and install it via the usual steps
#+begin_src bash
cd LCIO
mkdir build && cd build
cmake .. -GNinja \
    -DCMAKE_INSTALL_PREFIX=../install \
    -DCMAKE_CXX_STANDARD=17 \
    -DCMAKE_BUILD_TYPE=RelWithDebInfo
ninja install
#+end_src

Finally we make sure that we use this by adjusting the environment (assuming you
are still in the ~build~ folder)
#+begin_src  bash
export PATH=$(realpath ../install/bin):$PATH
export LD_LIBRARY_PATH=$(realpath ../install/lib):$LD_LIBRARY_PATH
export CMAKE_PREFIX_PATH=$(realpath ../install):$CMAKE_PREFIX_PATH
#+end_src

** Build a new standalone converter
We also have to rebuild the standalone converter to pick up the newly built LCIO
from above. Additionally, we want a version of the converter that converts
~TrackerHitPlane~ as ~TrackerHit~. For this we can use a dedicated branch
#+begin_src bash
git clone -b mucoll-conv-production https://github.com/tmadlener/k4EDM4hep2LcioConv
#+end_src

And then follow the usual steps for building
#+begin_src bash
cd k4EDM4hep2LcioConv
mkdir build && cd build
cmake .. -GNinja -DCMAKE_INSTALL_PREFIX=../install
ninja install
#+end_src

Finally setting up the environment again
#+begin_src bash
export PATH=$(realpath ../install/bin):$PATH
export LD_LIBRARY_PATH=$(realpath ../install/lib):$LD_LIBRARY_PATH
#+end_src

** Run conversion
- First we need to create a /patch file/ that allows us to have consistent event
contents (see the [[https://github.com/key4hep/k4EDM4hep2LcioConv/blob/master/doc/LCIO2EDM4hep.md][README]] for more details)
#+begin_src bash
check_missing_cols --minimal pionGun_REC.slcio > edm4hep_contents.txt
#+end_src
- Now we can run the converter
#+begin_src bash
lcio2edm4hep pionGun_REC.slcio pionGun_edm4hep.root edm4hep_contents.txt
#+end_src
- Finally we can have a peek at the file using ~podio-dump~
#+begin_src bash
podio-dump pionGun_edm4hep.root
#+end_src
*** Removing the ~SiTracks~ subset collection from conversion
- If you didn't make sure ot write the ~SiTrack~ collection as a full
  collection, you will have to remove it from being converted, to not run into
  this [[https://github.com/AIDASoft/podio/issues/462][issue in podio]]. This can easily be done by simply removing it from the
  config file for the conversion.
#+begin_src bash
sed -i '/SiTracks /d' edm4hep_contents.txt
#+end_src
